### ISSUE TITLE
Can't get token 

### ISSUE THREAD

**Issue by DariusAf** [Durgaprasad-Budhwani/azure-activedirectory-library-for-react-native#2]
Hi,
I encountered an issue when I tried to use the `.getAsyncToken()` method.

I have been able to prompt and successfully login using `.login()` and get the `userDetails` and the token with the callback. However, in order to refresh the token afterward, I want to use `.getAsyncToken()`, but I get a `ADAuthenticationErrorDomain `. Do you have any idea where this may come from ?

I roughly copied your example for the request : 

```
const { authority, resourceUri, clientId, redirectUri } = ...; 

export async function authenticate() {
  await AzureAdal.configure(authority, false, clientId, redirectUri, false);
  const userDetails = await AzureAdal.login(resourceUri);
  return userDetails;
}

export async function getToken() {
  await AzureAdal.configure(authority, false, clientId, redirectUri, false);
  const token = await AzureAdal.getTokenAsync(resourceUri);
  return token;
}
```

Then I called `authenticate` in a redux-saga and it worked just fine, but I could not get this `getToken` to work afterward.

Any suggestions ?

Thanks!

----
**Solution**

Ok, found it [in the docs of AzureAD](https://github.com/AzureAD/azure-activedirectory-library-for-objc), you need to add `com.microsoft.adalcache` on XCode in `Capabilities > Keychain Sharing`.

Hope that helps someone !

You should add this on the *README.md*.

**Comment by Durgaprasad-Budhwani** [comment]
Hi @DariusAf,

Thanks for using this library. Please use `getTokenAsync(resourceUri, loginHint)` for getting token.
loginHint is required.
